import { Compensation } from '@/schemas/compensationSchema'

export const compensationData: Compensation[] = [
  {
    id: "1",
    specialty: "Cardiology",
    yearsPostTraining: 5,
    baseSalary: 150000,
    annualBonusAmount: 20000,
    isFullTime: "Full Time",
    city: "New York",
    state: "NY",
    hospitalName: "ABC Hospital",
    // providerGender: "Male",
  },
  {
    id: "2",
    specialty: "Orthopedics",
    yearsPostTraining: 8,
    baseSalary: 180000,
    annualBonusAmount: 25000,
    isFullTime: "Full Time",
    city: "Los Angeles",
    state: "CA",
    hospitalName: "XYZ Medical Center",
    // providerGender: "Female",
  },
  {
    id: "3",
    specialty: "Pediatrics",
    yearsPostTraining: 3,
    baseSalary: 120000,
    annualBonusAmount: 15000,
    isFullTime: "Part Time",
    hoursPerWeek: 30,
    city: "Chicago",
    state: "IL",
    hospitalName: "123 Children's Hospital",
    // providerGender: "Male",
  },
  {
    id: "4",
    specialty: "Dermatology",
    yearsPostTraining: 10,
    baseSalary: 200000,
    annualBonusAmount: 30000,
    isFullTime: "Full Time",
    city: "Miami",
    state: "FL",
    hospitalName: "Sunshine Dermatology Clinic",
    // providerGender: "Female",
  },
  {
    id: "5",
    specialty: "Neurology",
    yearsPostTraining: 6,
    baseSalary: 160000,
    annualBonusAmount: 22000,
    isFullTime: "Full Time",
    city: "San Francisco",
    state: "CA",
    hospitalName: "Golden State Neurological Institute",
    // providerGender: "Male",
  },
  {
    id: "6",
    specialty: "Family Medicine",
    yearsPostTraining: 2,
    baseSalary: 100000,
    annualBonusAmount: 10000,
    isFullTime: "Part Time",
    hoursPerWeek: 35,
    city: "Austin",
    state: "TX",
    hospitalName: "Healthy Family Clinic",
    // providerGender: "Female",
  },
  {
    id: "7",
    specialty: "Ophthalmology",
    yearsPostTraining: 7,
    baseSalary: 180000,
    annualBonusAmount: 25000,
    isFullTime: "Full Time",
    city: "Boston",
    state: "MA",
    hospitalName: "Vision Care Center",
    // providerGender: "Male",
  },
  {
    id: "8",
    specialty: "Psychiatry",
    yearsPostTraining: 4,
    baseSalary: 140000,
    annualBonusAmount: 18000,
    isFullTime: "Full Time",
    city: "Seattle",
    state: "WA",
    hospitalName: "Mental Health Clinic",
    // providerGender: "Female",
  },
  {
    id: "9",
    specialty: "General Surgery",
    yearsPostTraining: 9,
    baseSalary: 190000,
    annualBonusAmount: 28000,
    isFullTime: "Full Time",
    city: "Houston",
    state: "TX",
    hospitalName: "Surgical Center of Excellence",
    // providerGender: "Male",
  },
  {
    id: "10",
    specialty: "Obstetrics and Gynecology",
    yearsPostTraining: 5,
    baseSalary: 160000,
    annualBonusAmount: 22000,
    isFullTime: "Part Time",
    hoursPerWeek: 30,
    city: "Denver",
    state: "CO",
    hospitalName: "Women's Health Associates",
    // providerGender: "Female",
  },
];
